name: detekt

on: push

jobs:
  static-code-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Executable Gradlew file
        run: chmod +x ./gradlew
      - name: Run detekt
        run: ./gradlew detekt
