name: detekt

on:
  pull_request:
    branches:
      - master
      - develop
      - release/*

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Executable Gradlew file
        run: chmod +x ./gradlew
      - name: Run detekt
        run: ./gradlew detekt
