name: Deploy Dokka Docs to GitHub Pages

on:
  push:
    tags:
      - 'v*'   # vで始まるタグ（例 v1.0.0）がpushされた時に実行
  workflow_dispatch:  # 手動トリガーを可能にする

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Executable Gradlew file
        run: chmod +x ./gradlew
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Build Dokka HTML
        run: ./gradlew dokkaHtml
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/html
