name: Deploy Dokka Docs to GitHub Pages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Executable Gradlew file
        run: chmod +x ./gradlew
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Build Dokka HTML
        id: build_dokka
        run: ./gradlew dokkaHtml
      - name: Commit
        if: steps.build_dokka.outcome == 'failure'
        run: |
          git config user.name "actions-user"
          git config user.email "action@github.com"
          git add .
          git commit -m "Auto commit code format"
          git push origin ${{ github.head_ref }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/html
